language: generic
sudo: required
services:
  - docker

branches:
  only:
    - master  

before_install:
  - docker build -t lina/docker-devmaestrofe -f Dockerfile.dev . 

script:
  - docker run -e CI=true lina/docker-devmaestrofe

after_success:
  - ssh -i testaws.pem ubuntu@ec2-3-17-150-160.us-east-2.compute.amazonaws.com yes
  - docker build -t lina/docker-maestrofe .
  - docker run -e CI=true lina/docker-maestrofe

notifications:
  email:
    recipients:
     - linaayman99@gmail.com
     - ahmhelmhalm@gmail.com
    on_success: change
    on_failure: always
